name: wordle-game
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_animate: ^4.2.0
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Bunu 3.0.0'dan 2.0.0'a düşürdük

flutter:
  uses-material-design: true
